### ISSUE TITLE
generate할때 오류남

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/tokyo#28]
```
generate
{ ValidationError: child "token" fails because [child "token_type" fails because ["token_option" is not allowed]]
    at Object.exports.process (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/joi/lib/errors.js:196:19)
    at internals.Object._validateWithOptions (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/joi/lib/types/any/index.js:675:31)
    at internals.Object.validate (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/joi/lib/types/any/index.js:709:21)
    at validate (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/tokyo-schema/dist/index.js:17:35)
    at new Builder (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/tokyo-solidity-template/dist/lib/Builder.js:37:56)
    at new Generator (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/tokyo-solidity-template/dist/lib/Generator.js:49:5)
    at Object.exports.default (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/node_modules/tokyo-solidity-template/dist/index.js:19:13)
    at Object.run (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/lib/commands/generate.js:16:29)
    at Command.run (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/lib/command.js:69:24)
    at Object.<anonymous> (/Users/kevin/.nvm/versions/node/v8.11.2/lib/node_modules/tokyo-cli/cli.js:13:9)
  isJoi: true,
  name: 'ValidationError',
  details:
   [ { message: '"token_option" is not allowed',
       path: [Array],
       type: 'object.allowUnknown',
       context: [Object] } ],
  _object:
   { project_name: 'RankingBall Gold',
     token:
      { token_type: [Object],
        token_name: 'RankingBall Gold',
        token_symbol: 'RBG',
        decimals: 18,
        use_custom_token: true },
     sale:
      { max_cap: '40000000000000000000000',
        min_cap: '5000000000000000000000',
        start_time: '2018/06/08 00:00:00',
        end_time: '2018/07/01 23:59:59',
        coeff: '10000',
        rate: [Object],
        distribution: [Object],
        stages: [Array],
        valid_purchase: [Object],
        new_token_owner: '0x557678cf28594495ef4b08a6447726f931f8d787' },
     multisig: { use_multisig: true, infos: [Array] },
     locker: { use_locker: true, beneficiaries: [Array] } },
  annotate: [Function] }
```

input파일은 채널에 있음

**Comment by ggs134** [comment]
input자료구조를 제대로 적어야 함.

token.token_type.token_option (x)
token.token_type (o)
token.token_option (o)

https://github.com/Onther-Tech/tokyo/blob/master/packages/tokyo-schema/README.md  파일은 수정이 필요함.
([29c92](https://github.com/Onther-Tech/tokyo/commit/29c9263b30939aeb9a3dcd4af65f906a25d595c4)) 커밋 기준.
