### ISSUE TITLE
truffle migrate --network ganache 에러

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/tokyo#30]
```
$ truffle migrate --network ganache
Using network 'ganache'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xa3cdfdc8115b8f060556e4001e5fe7ad8d5ce290d808d99df3e00dfb34768243
  Migrations: 0x81fa5aaf087ef84ecbbff1af240dc3e3626ab110
Saving successful migration to network...
  ... 0x7b640151979f6c98f17227005e352ed302923932be46e1af22258fdefd05acaf
Saving artifacts...
Running migration: 2_deploy_contracts.js

/usr/local/lib/node_modules/truffle/build/cli.bundled.js:61765
  throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^
/usr/local/lib/node_modules/truffle/build/cli.bundled.js:61765
  throw new Error("Could not find artifacts for " + import_path + " from any sources");
  ^

Error: Could not find artifacts for ./RankingBallGoldCustomToken from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:61765:9)
    at Object.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:73209:36)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209137:32)
    at /Users/kevin/dev/rankingball/out/migrations/2_deploy_contracts.js:18:25
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:115720:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

./RankingBallGoldCustomToken을 찾을 수 없다고 나옴

input파일에 
```JSON 
token.use_custom_token = true
```
로 넣어서 그런 것 같음

**Comment by ggs134** [comment]
1. https://github.com/Onther-Tech/rbg-crowdsale/blob/dev/project/contracts/RankingBallGoldCustomToken.sol 파일 추가(/contracts)
2. https://github.com/Onther-Tech/rbg-crowdsale/blob/dev/project/contracts/_import.sol 파일 추가(/contracts)
3. package.json파일 수정(https://github.com/Onther-Tech/rbg-crowdsale/blob/dev/project/package.json)
- dependencies, devDependencies수정

**Comment by 4000D** [comment]
2에서 추가한 _import.sol 은 테스트에서 사용하기 위해서 추가한거라, migration 에는 영향 안줄거에요
